---
- name: Check if matching {{ key_name }} GPG key already exists.
  ansible.builtin.shell:
    cmd: |-
      [ -f {{ _full_path | quote }} ] || exit 1
      gpg --list-keys --no-default-keyring --keyring {{ _full_path | quote }} {{ key_id or '' }} || exit 1
      exit 0
  register: should_download_gpg_key
  failed_when: should_download_gpg_key.rc not in (0, 1)
  changed_when: false

- name: Add {{ key_name }} GPG key.
  become: true
  block:
    - name: Download {{ key_name }} GPG key.
      ansible.builtin.get_url:
        url: "{{ url }}"
        dest: "{{ _full_path }}"

    - name: Dearmor {{ key_name }} GPG key.
      ansible.builtin.command:
        stdin: "{{ lookup('ansible.builtin.file', _full_path) }}"
        argv:
          - gpg
          - --dearmor
          - -o
          - "{{ _full_path }}"
      when: dearmor
  rescue:
    - name: Remove {{ key_name }} GPG key.
      ansible.builtin.file:
        path: "{{ _full_path }}"
        state: absent
    - name: Re-raise the error.
      fail:
        msg: "{{ ansible_failed_result }}"
  when: should_download_gpg_key.rc != 0
