---
- name: Check if matching {{ key_name }} GPG key already exists.
  ansible.builtin.shell:
    cmd: |-
      [ -f {{ _full_path | quote }} ] || exit 2
      gpg --list-keys --no-default-keyring --keyring {{ _full_path | quote }} {{ key_id or '' }}
      exit $?
  register: should_download_gpg_key
  failed_when: should_download_gpg_key.rc not in (0, 2)
  changed_when: false

- name: Add {{ key_name }} GPG key.
  become: true
  block:
    - name: Create temporary file for {{ key_name }}.
      ansible.builtin.tempfile:
        state: file
      register: asc_tempfile
      when: dearmor

    - name: Download {{ key_name }} GPG key.
      ansible.builtin.get_url:
        url: "{{ url }}"
        dest: "{{ asc_tempfile.path if dearmor else _full_path }}"

    - name: Dearmor {{ key_name }} GPG key.
      ansible.builtin.command:
        argv:
          - gpg
          # --yes is needed to successfully overwrite existing file with the same name
          - --yes
          - -o
          - "{{ _full_path }}"
          - --dearmor
          - "{{ asc_tempfile.path }}"
      when: dearmor
  always:
    - name: Remove temporary file for {{ key_name }}.
      ansible.builtin.file:
        path: "{{ asc_tempfile.path }}"
        state: absent
      when: dearmor

  when: should_download_gpg_key.rc != 0
